yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Legacy Repos
  title: Legacy Repos
  description: Legacy Repos
  labels:
    team: Legacy Repos
    environment: Legacy Repos
    language: Legacy Repos
    criticality: Legacy Repos
    region: Legacy Repos
spec:
  type: Legacy Repos
  owner: Legacy Repos
  lifecycle: Legacy Repos
  system: Legacy Repos
